name: image_cropper_for_web
description: A Flutter plugin for Web supports cropping images
publish_to: none
repository: https://github.com/amitvrm036/flutter_image_cropper
version: 2.0.0

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  
  image_cropper_platform_interface: 
    git:
        url: https://github.com/amitvrm036/flutter_image_cropper.git
        path: image_cropper_platform_interface

  js: ^0.6.3


dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0

flutter:
  plugin:
    implements: image_cropper
    platforms:
      web:
        pluginClass: ImageCropperPlugin
        fileName: image_cropper_for_web.dart
