name: image_cropper
description: A Flutter plugin for Android, iOS and Web supports cropping images
version: 4.0.1
publish_to: none
homepage: https://github.com/hnvn/flutter_image_cropper

environment:
  sdk: '>=2.18.0 <4.0.0'
  flutter: '>=3.3.0'

flutter:
  plugin:
    platforms:
      android:
        package: vn.hunghd.flutter.plugins.imagecropper
        pluginClass: ImageCropperPlugin
      ios:
        pluginClass: FLTImageCropperPlugin
      web:
        default_package: image_cropper_for_web

dependencies:
  flutter:
    sdk: flutter
  image_cropper_platform_interface: 
    git:
      url: https://github.com/amitvrm036/flutter_image_cropper.git
  image_cropper_for_web: ^2.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  plugin_platform_interface: ^2.0.0